name: test matrix

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: [0, 0, 0, 1]
    steps:
      - name: Echo job name
        run: exit ${{ matrix.image }}
  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: echo job status
        run: echo ${{ job.status }}
    
    
